#!/usr/bin/env bash
# installs nginx and configure it

sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
