#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer

sudo apt-get update
sudo apt-get upgrade -y
sudo apt install haproxy -y
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg
sudo echo "ENABLED-=1">> /etc/default/haproxy
sudo echo "frontend http_front
	bind *.80
	stats url /haproxy?stats
	defualt_backend http_back
backend http_back
	balance roundrobin
	server 36694-web-01 100.25.169.42:80 check
	server 36694-web-02 54.157.182.46:80 check" >> /etc/haproxy/haproxy.cfg
wget /downloads/haproxy/haproxy.init -O /etc/init.d/haproxy
sudo service haproxy start
