#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer

sudo apt-get update -y
sudo apt-get install haproxy -y
config="\\nfrontend haproxy-main\n\tbind *:80\n\tmode http\n\tdefault_backend nginx_webservers\n\nbackend nginx_webservers\n\tbalance roundrobin\n\tserver web-01 100.25.169.42:80 check\n\tserver web-02   54.157.182.46:80 check\n"
echo -e $config | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
